name: 'clear_result_temp'
version: '1.0.0'
config-version: 2

# 项目级别的配置
profile: 'clear_result_temp'

# 模型配置
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# 模型配置
models:
  clear_result_temp:
    # 全局 pre-hook：在运行任何模型前先选择数据库
    # 注意：使用模型配置的schema，而不是target.schema，避免schema重复
    +pre-hook: "USE CLEAR"
    # 中间表模型
    intermediate:
      materialized: table
      schema: "CLEAR"
    # 其他模型
    +materialized: view
