@startuml 省中心联网收费业务实体关系图
skinparam linetype ortho
hide circle

车辆 "1" ||--|| "n" 通行介质 : "持有"
车辆 "1" ||--o{ "n" 交易流水 : "关联"

路段业主  "1" ||--o{ "n" 收费公路 : "管理"
收费公路 "1" ||--o{ "n" 收费站 : "包含"
收费公路 "1" ||--o{ "n" ETC门架 : "包含"
收费公路 "1" ||--o{ "n" 收费单元 : "包含"
ETC门架 "1" ||--o{ "n" 收费单元 : "代收"
收费站 "1" ||--o{ "n" 车道 : "包含"


ETC门架 "1" ||--o{ "1" 标识点 : "继承"
车道 "1" ||--o{ "1" 标识点 : "继承"

标识点 "1" ||--o{ "n" 交易流水 : "生成"

交易流水 "n" ||--o{ "1" 车辆通行路径 : "汇聚为"
车辆通行路径 "1" ||--o{ "1" 通行拟合路径 : "拟合为"

通行拟合路径 "1" ||--o{ "n" 拆分明细 : "拆分为"
收费单元 "1" ||--|| "1" 拆分明细 : "关联"

@enduml
