-- gsdb.clearreport definition

CREATE TABLE `clearreport` (
  `id` varchar(255) NOT NULL,
  `alipay_op_split_money` varchar(18) DEFAULT NULL COMMENT '支付宝操作拆分金额',
  `alipay_split_money` varchar(18) DEFAULT NULL COMMENT '支付宝拆分金额',
  `cash_op_split_money` varchar(18) DEFAULT NULL COMMENT '现金操作拆分金额',
  `union_op_split_money` varchar(18) DEFAULT NULL COMMENT '联合操作拆分金额',
  `union_split_money` varchar(18) DEFAULT NULL COMMENT '联合拆分金额',
  `cash_op_toll_money` varchar(18) DEFAULT NULL COMMENT '现金操作合计金额',
  `wepay_toll_money` varchar(18) DEFAULT NULL COMMENT '微信合计金额',
  `gen_time` date DEFAULT NULL COMMENT '生成时间',
  `other_split_money` varchar(18) DEFAULT NULL COMMENT '其他拆分金额',
  `etc_op_split_money` varchar(18) DEFAULT NULL COMMENT 'ETC操作拆分金额',
  `alipay_op_toll_money` varchar(18) DEFAULT NULL COMMENT '支付宝操作合计金额',
  `crop_id` int DEFAULT NULL COMMENT '收费路段业主',
  `wepay_op_toll_money` varchar(18) DEFAULT NULL COMMENT '微信操作合计金额',
  `alipay_return_money` varchar(18) DEFAULT NULL COMMENT '支付宝退费金额',
  `wepay_return_money` varchar(18) DEFAULT NULL COMMENT '微信退费金额',
  `pay_card_type` int DEFAULT NULL COMMENT '支付卡类型',
  `etc_split_money` varchar(18) DEFAULT NULL COMMENT 'ETC拆分金额',
  `etc_toll_money` varchar(18) DEFAULT NULL COMMENT 'ETC合计金额',
  `l_date` date DEFAULT NULL COMMENT '逻辑日期',
  `cash_return_money` varchar(18) DEFAULT NULL COMMENT '现金退费金额',
  `union_return_money` varchar(18) DEFAULT NULL COMMENT '联合退费金额',
  `wepay_split_money` varchar(18) DEFAULT NULL COMMENT '微信拆分金额',
  `other_return_money` varchar(18) DEFAULT NULL COMMENT '其他退费金额',
  `alipay_toll_money` varchar(18) DEFAULT NULL COMMENT '支付宝合计金额',
  `cash_split_money` varchar(18) DEFAULT NULL COMMENT '现金拆分金额',
  `other_toll_money` varchar(18) DEFAULT NULL COMMENT '其他合计金额',
  `etc_op_toll_money` varchar(18) DEFAULT NULL COMMENT 'ETC操作合计金额',
  `split_org` varchar(255) DEFAULT NULL COMMENT '拆分机构',
  `other_op_split_money` varchar(18) DEFAULT NULL COMMENT '其他操作拆分金额',
  `cash_toll_money` varchar(18) DEFAULT NULL COMMENT '现金合计金额',
  `wepay_op_split_money` varchar(18) DEFAULT NULL COMMENT '微信操作拆分金额',
  `money_flag` int DEFAULT NULL COMMENT '金额标志',
  `org_type` int DEFAULT NULL COMMENT '机构类型',
  `clear_date` date DEFAULT NULL COMMENT '清分日期',
  `road_id` varchar(255) DEFAULT NULL COMMENT '收费公路',
  `union_op_toll_money` varchar(18) DEFAULT NULL COMMENT '联合操作合计金额',
  `etc_return_money` varchar(18) DEFAULT NULL COMMENT 'ETC退费金额',
  `other_op_toll_money` varchar(18) DEFAULT NULL COMMENT '其他操作合计金额',
  `union_toll_money` varchar(18) DEFAULT NULL COMMENT '联合合计金额',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='清分报表同步表';


-- gsdb.clearresult definition

CREATE TABLE `clearresult` (
  `id` varchar(255) NOT NULL,
  `transaction_id` varchar(255) DEFAULT NULL COMMENT '交易编号',
  `amount` varchar(18) DEFAULT NULL COMMENT '实收清分金额',
  `pass_id` varchar(255) DEFAULT NULL COMMENT '通行标识',
  `pay_card_type` int DEFAULT NULL COMMENT '支付卡类型',
  `l_date` date DEFAULT NULL COMMENT '逻辑日',
  `interval_id` varchar(255) DEFAULT NULL COMMENT '收费单元编号',
  `discount_amount` varchar(18) DEFAULT NULL COMMENT '优惠清分金额',
  `pay_type` int DEFAULT NULL COMMENT '支付方式',
  `clear_date` date DEFAULT NULL COMMENT '清分日期',
  `crop_id` int DEFAULT NULL COMMENT '收费路段业主',
  `road_id` varchar(255) DEFAULT NULL COMMENT '收费公路',
  `charge_amount` varchar(18) DEFAULT NULL COMMENT '应收清分金额',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='清分结果同步表';


-- gsdb.entrytransaction definition

CREATE TABLE `entrytransaction` (
  `vlpc` int DEFAULT NULL COMMENT '车牌颜色',
  `limit_weight` int DEFAULT NULL COMMENT '限载总重(kg)',
  `media_type` int DEFAULT NULL COMMENT '通行介质类型',
  `en_time` varchar(200) DEFAULT NULL COMMENT '入口时间',
  `en_toll_lane_id` varchar(200) DEFAULT NULL COMMENT '入口车道号(国标)',
  `oper_name` varchar(200) DEFAULT NULL COMMENT '操作员姓名',
  `en_axle_count` int DEFAULT NULL COMMENT '入口轴数',
  `pass_id` varchar(200) DEFAULT NULL COMMENT '通行标识ID',
  `receive_time` varchar(200) DEFAULT NULL COMMENT '接收时间',
  `description` int DEFAULT NULL COMMENT '对交易的文字解释',
  `axis_info` int DEFAULT NULL COMMENT '轴组信息',
  `en_weight` int DEFAULT NULL COMMENT '入口重量',
  `id` varchar(200) NOT NULL COMMENT '交易流水号',
  `vlp` varchar(200) DEFAULT NULL COMMENT '车牌号',
  `station_receive_time` varchar(200) DEFAULT NULL COMMENT '站级接收时间',
  `trans_type` varchar(200) DEFAULT NULL COMMENT '交易类型',
  `over_weight_rate` int DEFAULT NULL COMMENT '超限率',
  `trans_code` varchar(200) DEFAULT NULL COMMENT '交易编码',
  `trans_fee` int DEFAULT NULL COMMENT '卡面扣费金额',
  `sp_info` varchar(200) DEFAULT NULL COMMENT '业务分析特情状态',
  `identify_vlp` varchar(200) DEFAULT NULL COMMENT '识别车牌号',
  `direction` int DEFAULT NULL COMMENT '行驶方向',
  `balance_before` varchar(200) DEFAULT NULL COMMENT '交易前余额（分）',
  `identify_vlpc` int DEFAULT NULL COMMENT '识别车牌颜色',
  `special_type` varchar(200) DEFAULT NULL COMMENT '部特情类型',
  `l_date` varchar(200) DEFAULT NULL COMMENT '逻辑日期',
  `lane_sp_info` varchar(300) DEFAULT NULL COMMENT '车道特情状态',
  `oper_id` varchar(200) DEFAULT NULL COMMENT '操作员工号',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='入口车道流水同步表';


-- gsdb.exittransaction definition

CREATE TABLE `exittransaction` (
  `ID` longtext,
  `PASSID` longtext,
  `SOURCEID` longtext,
  `RETURNMONEYSN` longtext,
  `LDATE` datetime DEFAULT NULL,
  `EXTIME` datetime DEFAULT NULL,
  `STATIONRECEIVETIME` datetime DEFAULT NULL,
  `RECEIVETIME` datetime DEFAULT NULL,
  `OPERID` longtext,
  `OPERNAME` longtext,
  `EXTOLLLANEID` longtext,
  `EXTOLLSTATIONID` longtext,
  `EXTOLLSTATIONNAME` longtext,
  `MEDIATYPE` int DEFAULT NULL,
  `MEDIANO` longtext,
  `EXVLP` longtext,
  `EXVLPC` int DEFAULT NULL,
  `IDENTIFYVLP` longtext,
  `IDENTIFYVLPC` int DEFAULT NULL,
  `TRANSCODE` longtext,
  `TRANSTYPE` longtext,
  `MULTIPROVINCE` int DEFAULT NULL,
  `PROVINCEGROUP` longtext,
  `TOLLPROVINCEID` longtext,
  `TRANSPAYTYPE` int DEFAULT NULL,
  `PAYTYPE` int DEFAULT NULL,
  `PAYCARDID` longtext,
  `AXLECOUNT` int DEFAULT NULL,
  `AXISINFO` longtext,
  `EXWEIGHT` int DEFAULT NULL,
  `LIMITWEIGHT` int DEFAULT NULL,
  `OVERWEIGHTRATE` int DEFAULT NULL,
  `DESCRIPTION` longtext,
  `VSPEED` int DEFAULT NULL,
  `SPECIALTYPE` longtext,
  `LANESPINFO` longtext,
  `SPINFO` longtext,
  `MODIFYFLAG` int DEFAULT NULL,
  `TOLLDISTANCE` int DEFAULT NULL,
  `REALDISTANCE` int DEFAULT NULL,
  `FREETYPE` int DEFAULT NULL,
  `FREEMODE` int DEFAULT NULL,
  `FREEINFO` longtext,
  `TRANSFEE` bigint DEFAULT NULL,
  `BALANCEBEFORE` bigint DEFAULT NULL,
  `BALANCEAFTER` bigint DEFAULT NULL,
  `FEE` bigint DEFAULT NULL,
  `DISCOUNTFEE` bigint DEFAULT NULL,
  `PAYFEE` bigint DEFAULT NULL,
  `OBUPAYFEE` bigint DEFAULT NULL,
  `OBUDISCOUNTFEE` bigint DEFAULT NULL,
  `FEEMILEAGE` bigint DEFAULT NULL,
  `COLLECTFEE` bigint DEFAULT NULL,
  `REBATEMONEY` bigint DEFAULT NULL,
  `CARDCOSTFEE` bigint DEFAULT NULL,
  `UNPAYFEE` bigint DEFAULT NULL,
  `UNPAYFLAG` longtext,
  `UNPAYCARDCOST` bigint DEFAULT NULL,
  `TICKETFEE` bigint DEFAULT NULL,
  `ENTOLLMONEY` bigint DEFAULT NULL,
  `ENFREEMONEY` bigint DEFAULT NULL,
  `ENLASTMONEY` bigint DEFAULT NULL,
  `EXITEXTLIST` longtext,
  `ACTUALFEECLASS` int DEFAULT '1'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- gsdb.gantrytransaction definition

CREATE TABLE `gantrytransaction` (
  `TRADEID` longtext,
  `PASSID` longtext,
  `TRANSTIME` datetime DEFAULT NULL,
  `RECORDGENTIME` datetime DEFAULT NULL,
  `RECEIVETIME` datetime DEFAULT NULL,
  `GANTRYID` longtext,
  `GANTRYTYPE` longtext,
  `ORIGINALFLAG` int DEFAULT NULL,
  `GANTRYHEX` longtext,
  `LASTGANTRYHEX` longtext,
  `LASTGANTRYTIME` datetime DEFAULT NULL,
  `MEDIATYPE` int DEFAULT NULL,
  `CPUCARDID` longtext,
  `VLP` longtext,
  `VLPC` int DEFAULT NULL,
  `VEHICLETYPE` int DEFAULT NULL,
  `IDENTIFYVEHICLETYPE` int DEFAULT NULL,
  `TRADETYPE` int DEFAULT NULL,
  `AXLECOUNT` int DEFAULT NULL,
  `TOTALWEIGHT` int DEFAULT NULL,
  `VEHICLELENGTH` int DEFAULT NULL,
  `VEHICLEWIDTH` int DEFAULT NULL,
  `VEHICLEHIGHT` int DEFAULT NULL,
  `FEEMILEAGE` int DEFAULT NULL,
  `TRANSFEE` bigint DEFAULT NULL,
  `BALANCEBEFORE` bigint DEFAULT NULL,
  `BALANCEAFTER` bigint DEFAULT NULL,
  `PAYFEE` bigint DEFAULT NULL,
  `FEE` bigint DEFAULT NULL,
  `DISCOUNTFEE` bigint DEFAULT NULL,
  `TOLLINTERVALID` longtext,
  `TOLLINTERVALSIGN` longtext,
  `PAYFEEGROUP` longtext,
  `FEEGROUP` longtext,
  `DISCOUNTFEEGROUP` longtext,
  `DESCRIPTION` longtext,
  `FEECALCSPECIAL` int DEFAULT NULL,
  `CHARGESSPECIALTYPE` longtext,
  `ISFIXDATA` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- gsdb.`path` definition

CREATE TABLE `path` (
  `id` varchar(255) NOT NULL,
  `plate_color` int DEFAULT NULL COMMENT '车牌颜色',
  `en_time` varchar(200) DEFAULT NULL COMMENT '入口时间',
  `ex_toll_lane_id` varchar(200) DEFAULT NULL COMMENT '出口车道编号',
  `en_toll_lane_id` varchar(200) DEFAULT NULL COMMENT '入口车道编号',
  `ex_vehicle_type` int DEFAULT NULL COMMENT '出口车辆类型',
  `en_toll_station_id` varchar(200) DEFAULT NULL COMMENT '入口收费站编号',
  `pay_type` int DEFAULT NULL COMMENT '支付类型',
  `ex_toll_station_id` varchar(200) DEFAULT NULL COMMENT '出口收费站编号',
  `pay_card_type` int DEFAULT NULL COMMENT '支付卡类型',
  `pass_id` varchar(200) DEFAULT NULL COMMENT '通行标识',
  `plate_num` varchar(200) DEFAULT NULL COMMENT '车牌号码',
  `l_date` varchar(100) DEFAULT NULL COMMENT '逻辑日期',
  `ex_time` varchar(200) DEFAULT NULL COMMENT '出口时间',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='车辆通行路径同步表';


-- gsdb.pathdetail definition

CREATE TABLE `pathdetail` (
  `ID` longtext,
  `PASSID` longtext,
  `PLATENUM` longtext,
  `PLATECOLOR` int DEFAULT NULL,
  `IDENTIFYPOINTID` longtext,
  `IDENTIFYPOINTHEX` longtext,
  `INTERVALS` longtext,
  `FEE` longtext,
  `PAYFEE` longtext,
  `DISCOUNTFEE` longtext,
  `TRANSTIME` longtext
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- gsdb.splitdetail definition

CREATE TABLE `splitdetail` (
  `id` varchar(255) NOT NULL,
  `toll_interval_pay_fee` varchar(200) DEFAULT NULL COMMENT '收费单元支付费用',
  `toll_interval_fee` varchar(200) DEFAULT NULL COMMENT '收费单元费用',
  `pass_id` varchar(200) NOT NULL COMMENT '通行标识',
  `interval_id` varchar(200) NOT NULL COMMENT '收费单元编号',
  `split_remark` varchar(200) DEFAULT NULL COMMENT '拆分备注',
  `pro_split_time` varchar(200) DEFAULT NULL COMMENT '拆分时间',
  `pro_split_type` int DEFAULT NULL COMMENT '拆分原则',
  `transaction_id` varchar(200) NOT NULL COMMENT '交易编号',
  `split_flag` int DEFAULT NULL COMMENT '拆分标志',
  `toll_interval_discount_fee` varchar(200) DEFAULT NULL COMMENT '收费单元优惠费用',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='拆分明细同步表';


-- gsdb.tollgantry definition

CREATE TABLE `tollgantry` (
  `veh_detector_uid` varchar(256) DEFAULT NULL COMMENT '车辆检测器管理唯一标识',
  `snmp_version` varchar(8) DEFAULT NULL COMMENT 'SNMP协议版本',
  `lng` varchar(20) NOT NULL COMMENT '门架地理位置经度',
  `end_time` datetime NOT NULL COMMENT '门架停止运行时间',
  `load_detection_model` varchar(256) DEFAULT NULL COMMENT '载重检测器设备型号',
  `secret_key` varchar(256) DEFAULT NULL COMMENT 'SNMP秘钥',
  `equipment_ip` varchar(64) DEFAULT NULL COMMENT '设备IP地址',
  `vplr_id` varchar(512) NOT NULL COMMENT 'VPLR设备ID',
  `weather_detector_uid` varchar(256) DEFAULT NULL COMMENT '天气检测器管理唯一标识',
  `status` bigint NOT NULL COMMENT '门架运行状态',
  `receive_time` datetime DEFAULT NULL COMMENT '数据接收时间',
  `community` varchar(128) DEFAULT NULL COMMENT 'SNMP团体名',
  `rsu_man_uid` varchar(256) NOT NULL COMMENT 'RSU(路侧单元)管理唯一标识',
  `id` varchar(19) NOT NULL COMMENT '主键ID',
  `veh_detector_model` varchar(256) DEFAULT NULL COMMENT '车辆检测器设备型号',
  `load_detection_uid` varchar(256) DEFAULT NULL COMMENT '载重检测器管理唯一标识',
  `security_name` varchar(128) DEFAULT NULL COMMENT 'SNMP安全名',
  `type` bigint NOT NULL COMMENT '收费门架类型',
  `operators` varchar(8) NOT NULL COMMENT '系统操作员信息',
  `response_info` varchar(1024) DEFAULT NULL COMMENT '系统响应信息',
  `batch_file_name` varchar(128) DEFAULT NULL COMMENT '数据处理批次文件名',
  `line_type` varchar(8) NOT NULL COMMENT '通信线路类型',
  `reetc_gantry_hex` varchar(10) DEFAULT NULL COMMENT '重ETC门架的十六进制标识',
  `controller_id` varchar(256) NOT NULL COMMENT '控制器设备ID',
  `snmp_port` bigint DEFAULT NULL COMMENT 'SNMP协议端口号',
  `record_gen_time` datetime NOT NULL COMMENT '数据记录生成时间',
  `power_controller_model` varchar(256) DEFAULT NULL COMMENT '电源控制器设备型号',
  `veh_detector_id` varchar(256) DEFAULT NULL COMMENT '车辆检测器设备ID',
  `name` varchar(150) DEFAULT NULL COMMENT '收费门架名称',
  `class_detector_uid` varchar(256) DEFAULT NULL COMMENT '车型检测器管理唯一标识',
  `use_status` bigint NOT NULL COMMENT '设备使用状态',
  `pile_number` varchar(20) NOT NULL COMMENT '门架所在位置的桩号',
  `temp_controller_id` varchar(256) DEFAULT NULL COMMENT '温度控制器设备ID',
  `agency_gantry_ids` varchar(19) DEFAULT NULL COMMENT '关联的机构门架ID列表',
  `start_time` datetime NOT NULL COMMENT '门架开始运行时间',
  `lane_count` varchar(10) DEFAULT NULL COMMENT '门架覆盖的车道数量',
  `etc_gantry_hex` varchar(512) NOT NULL COMMENT 'ETC门架的十六进制标识',
  `weather_detector_id` varchar(256) DEFAULT NULL COMMENT '天气检测器设备ID',
  `safe_equip_id` varchar(256) DEFAULT NULL COMMENT '安全设备设备ID',
  `boundary_type` bigint DEFAULT NULL COMMENT '门架边界类型',
  `server_db_ver` varchar(256) NOT NULL COMMENT '服务器数据库版本号',
  `pro_time` datetime DEFAULT NULL COMMENT '数据处理完成时间',
  `weather_detector_model` varchar(256) DEFAULT NULL COMMENT '天气检测器设备型号',
  `response_code` bigint NOT NULL COMMENT '系统响应代码',
  `vplr_uid` varchar(256) NOT NULL COMMENT 'VPLR(车牌识别设备)管理唯一标识',
  `power_controller_uid` varchar(256) DEFAULT NULL COMMENT '电源控制器管理唯一标识',
  `encryption` varchar(256) DEFAULT NULL COMMENT 'SNMP加密方式',
  `toll_intervals` varchar(512) NOT NULL COMMENT '收费区间信息',
  `gantry_sign` varchar(10) DEFAULT NULL COMMENT '门架标识信息',
  `server_id` varchar(256) NOT NULL COMMENT '服务器设备ID',
  `vplr_model` varchar(256) NOT NULL COMMENT 'VPLR设备型号',
  `security_level` varchar(16) DEFAULT NULL COMMENT 'SNMP安全级别',
  `authentication` varchar(256) DEFAULT NULL COMMENT 'SNMP认证方式',
  `hdv_uid` varchar(256) NOT NULL COMMENT 'HDV(高清视频设备)管理唯一标识',
  `auth_key` varchar(512) DEFAULT NULL COMMENT 'SNMP认证密钥',
  `data_merge_point` varchar(64) NOT NULL COMMENT '数据合并点标识',
  `controller_uid` varchar(256) NOT NULL COMMENT '控制器管理唯一标识',
  `safe_equip_uid` varchar(256) DEFAULT NULL COMMENT '安全设备管理唯一标识',
  `server_uid` varchar(256) NOT NULL COMMENT '服务器管理唯一标识',
  `power_controller_id` varchar(256) DEFAULT NULL COMMENT '电源控制器设备ID',
  `safe_equip_model` varchar(256) DEFAULT NULL COMMENT '安全设备设备型号',
  `hdv_id` varchar(512) NOT NULL COMMENT 'HDV设备ID',
  `rsu_id` varchar(512) NOT NULL COMMENT 'RSU设备ID',
  `temp_controller_uid` varchar(256) DEFAULT NULL COMMENT '温度控制器管理唯一标识',
  `rsu_model` varchar(256) NOT NULL COMMENT 'RSU设备型号',
  `server_sys_ver` varchar(256) NOT NULL COMMENT '服务器系统版本号',
  `load_detection_id` varchar(256) DEFAULT NULL COMMENT '载重检测器设备ID',
  `controller_model` varchar(256) NOT NULL COMMENT '控制器设备型号',
  `imei` varchar(64) DEFAULT NULL COMMENT '设备IMEI号码',
  `hdv_model` varchar(256) NOT NULL COMMENT 'HDV设备型号',
  `operation` bigint NOT NULL COMMENT '系统操作类型',
  `class_detector_model` varchar(256) DEFAULT NULL COMMENT '车型检测器设备型号',
  `temp_controller_model` varchar(256) DEFAULT NULL COMMENT '温度控制器设备型号',
  `server_model` varchar(256) NOT NULL COMMENT '服务器设备型号',
  `lat` varchar(20) NOT NULL COMMENT '门架地理位置纬度',
  `controller_sys_ver` varchar(256) NOT NULL COMMENT '控制器系统版本号',
  `class_detector_id` varchar(256) DEFAULT NULL COMMENT '车型检测器设备ID',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='收费门架同步表';


-- gsdb.tollinterval definition

CREATE TABLE `tollinterval` (
  `response_code` bigint NOT NULL COMMENT '系统响应代码',
  `section_id` varchar(16) DEFAULT NULL COMMENT 'id截取前11位为路段ID',
  `end_lng` varchar(20) DEFAULT NULL COMMENT '终点经度',
  `start_stake_num` varchar(20) NOT NULL COMMENT '起点桩号',
  `end_time` datetime NOT NULL COMMENT '收费单元结束时间',
  `length` bigint NOT NULL COMMENT '收费单元长度',
  `end_lat` varchar(20) DEFAULT NULL COMMENT '终点纬度',
  `vertical_section_type` bigint DEFAULT NULL COMMENT '垂直断面类型',
  `receive_time` datetime DEFAULT NULL COMMENT '数据接收时间',
  `status` bigint DEFAULT NULL COMMENT '收费单元状态',
  `id` varchar(16) NOT NULL COMMENT '主键ID',
  `type` bigint NOT NULL COMMENT '收费单元类型',
  `response_info` varchar(1024) DEFAULT NULL COMMENT '系统响应信息',
  `batch_file_name` varchar(128) DEFAULT NULL COMMENT '批次处理文件名',
  `start_lat` varchar(20) DEFAULT NULL COMMENT '起点纬度',
  `start_lng` varchar(20) DEFAULT NULL COMMENT '起点经度',
  `begin_time` datetime NOT NULL COMMENT '收费单元开始时间',
  `direction` bigint DEFAULT NULL COMMENT '通行方向',
  `record_gen_time` datetime NOT NULL COMMENT '记录生成时间',
  `end_stake_num` varchar(20) NOT NULL COMMENT '终点桩号',
  `name` varchar(150) NOT NULL COMMENT '收费单元名称',
  `operation` bigint NOT NULL COMMENT '操作类型',
  `province_type` bigint NOT NULL COMMENT '省份类型',
  `pro_time` datetime DEFAULT NULL COMMENT '系统处理时间',
  `toll_roads` varchar(150) NOT NULL COMMENT '收费道路信息',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='收费单元同步表';


-- gsdb.tollsection definition

CREATE TABLE `tollsection` (
  `ID` longtext,
  `ROADID` longtext,
  `NAME` longtext,
  `SECTIONOWNERID` longtext,
  `TYPE` bigint DEFAULT NULL,
  `LENGTH` bigint DEFAULT NULL,
  `STARTSTAKENUM` longtext,
  `STARTLAT` longtext,
  `STARTLNG` longtext,
  `ENDSTAKENUM` longtext,
  `ENDLAT` longtext,
  `ENDLNG` longtext,
  `TAX` bigint DEFAULT NULL,
  `TAXRATE` decimal(38,18) DEFAULT NULL,
  `CHARGETYPE` bigint DEFAULT NULL,
  `TOLLROADS` longtext,
  `BUILTTIME` datetime DEFAULT NULL,
  `STARTTIME` datetime DEFAULT NULL,
  `ENDTIME` datetime DEFAULT NULL,
  `OPERATION` bigint DEFAULT NULL,
  `RECORDGENTIME` datetime DEFAULT NULL,
  `STATUS` longtext,
  `BATCHFILENAME` longtext,
  `RESPONSECODE` bigint DEFAULT NULL,
  `RESPONSEINFO` longtext,
  `RECEIVETIME` datetime DEFAULT NULL,
  `PROTIME` datetime DEFAULT NULL,
  `NEXTTAXRATE` decimal(38,18) DEFAULT NULL,
  `NEXTRATEDATE` datetime DEFAULT NULL,
  `SECTIONLEVEL` bigint DEFAULT NULL,
  `ONLINETYPE` bigint DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;