-- gsdb310.clearreport definition

CREATE TABLE `clearreport` (
  `id` varchar(255) NOT NULL,
  `alipay_op_split_money` varchar(18) DEFAULT NULL COMMENT '支付宝操作拆分金额',
  `alipay_split_money` varchar(18) DEFAULT NULL COMMENT '支付宝拆分金额',
  `cash_op_split_money` varchar(18) DEFAULT NULL COMMENT '现金操作拆分金额',
  `union_op_split_money` varchar(18) DEFAULT NULL COMMENT '联合操作拆分金额',
  `union_split_money` varchar(18) DEFAULT NULL COMMENT '联合拆分金额',
  `cash_op_toll_money` varchar(18) DEFAULT NULL COMMENT '现金操作合计金额',
  `wepay_toll_money` varchar(18) DEFAULT NULL COMMENT '微信合计金额',
  `gen_time` date DEFAULT NULL COMMENT '生成时间',
  `other_split_money` varchar(18) DEFAULT NULL COMMENT '其他拆分金额',
  `etc_op_split_money` varchar(18) DEFAULT NULL COMMENT 'ETC操作拆分金额',
  `alipay_op_toll_money` varchar(18) DEFAULT NULL COMMENT '支付宝操作合计金额',
  `crop_id` int DEFAULT NULL COMMENT '收费路段业主',
  `wepay_op_toll_money` varchar(18) DEFAULT NULL COMMENT '微信操作合计金额',
  `alipay_return_money` varchar(18) DEFAULT NULL COMMENT '支付宝退费金额',
  `wepay_return_money` varchar(18) DEFAULT NULL COMMENT '微信退费金额',
  `pay_card_type` int DEFAULT NULL COMMENT '支付卡类型',
  `etc_split_money` varchar(18) DEFAULT NULL COMMENT 'ETC拆分金额',
  `etc_toll_money` varchar(18) DEFAULT NULL COMMENT 'ETC合计金额',
  `l_date` date DEFAULT NULL COMMENT '逻辑日期',
  `cash_return_money` varchar(18) DEFAULT NULL COMMENT '现金退费金额',
  `union_return_money` varchar(18) DEFAULT NULL COMMENT '联合退费金额',
  `wepay_split_money` varchar(18) DEFAULT NULL COMMENT '微信拆分金额',
  `other_return_money` varchar(18) DEFAULT NULL COMMENT '其他退费金额',
  `alipay_toll_money` varchar(18) DEFAULT NULL COMMENT '支付宝合计金额',
  `cash_split_money` varchar(18) DEFAULT NULL COMMENT '现金拆分金额',
  `other_toll_money` varchar(18) DEFAULT NULL COMMENT '其他合计金额',
  `etc_op_toll_money` varchar(18) DEFAULT NULL COMMENT 'ETC操作合计金额',
  `split_org` varchar(255) DEFAULT NULL COMMENT '拆分机构',
  `other_op_split_money` varchar(18) DEFAULT NULL COMMENT '其他操作拆分金额',
  `cash_toll_money` varchar(18) DEFAULT NULL COMMENT '现金合计金额',
  `wepay_op_split_money` varchar(18) DEFAULT NULL COMMENT '微信操作拆分金额',
  `money_flag` int DEFAULT NULL COMMENT '金额标志',
  `org_type` int DEFAULT NULL COMMENT '机构类型',
  `clear_date` date DEFAULT NULL COMMENT '清分日期',
  `road_id` varchar(255) DEFAULT NULL COMMENT '收费公路',
  `union_op_toll_money` varchar(18) DEFAULT NULL COMMENT '联合操作合计金额',
  `etc_return_money` varchar(18) DEFAULT NULL COMMENT 'ETC退费金额',
  `other_op_toll_money` varchar(18) DEFAULT NULL COMMENT '其他操作合计金额',
  `union_toll_money` varchar(18) DEFAULT NULL COMMENT '联合合计金额',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='清分报表同步表';


-- gsdb310.clearresult definition

CREATE TABLE `clearresult` (
  `id` varchar(255) NOT NULL,
  `transaction_id` varchar(255) DEFAULT NULL COMMENT '交易编号',
  `amount` varchar(18) DEFAULT NULL COMMENT '实收清分金额',
  `pass_id` varchar(255) DEFAULT NULL COMMENT '通行标识',
  `pay_card_type` int DEFAULT NULL COMMENT '支付卡类型',
  `l_date` date DEFAULT NULL COMMENT '逻辑日',
  `interval_id` varchar(255) DEFAULT NULL COMMENT '收费单元编号',
  `discount_amount` varchar(18) DEFAULT NULL COMMENT '优惠清分金额',
  `pay_type` int DEFAULT NULL COMMENT '支付方式',
  `clear_date` date DEFAULT NULL COMMENT '清分日期',
  `crop_id` int DEFAULT NULL COMMENT '收费路段业主',
  `road_id` varchar(255) DEFAULT NULL COMMENT '收费公路',
  `charge_amount` varchar(18) DEFAULT NULL COMMENT '应收清分金额',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='清分结果同步表';


-- gsdb310.entrytransaction definition

CREATE TABLE `entrytransaction` (
  `vlpc` int DEFAULT NULL COMMENT '车牌颜色',
  `limit_weight` int DEFAULT NULL COMMENT '限载总重(kg)',
  `media_type` int DEFAULT NULL COMMENT '通行介质类型',
  `card_net` varchar(20) DEFAULT NULL COMMENT '卡网络号(如3701=山东省)',
  `en_time` varchar(200) DEFAULT NULL COMMENT '入口时间',
  `en_toll_lane_id` varchar(200) DEFAULT NULL COMMENT '入口车道号(国标)',
  `oper_name` varchar(200) DEFAULT NULL COMMENT '操作员姓名',
  `en_axle_count` int DEFAULT NULL COMMENT '入口轴数',
  `pass_id` varchar(200) DEFAULT NULL COMMENT '通行标识ID',
  `receive_time` varchar(200) DEFAULT NULL COMMENT '接收时间',
  `description` int DEFAULT NULL COMMENT '对交易的文字解释',
  `axis_info` int DEFAULT NULL COMMENT '轴组信息',
  `en_weight` int DEFAULT NULL COMMENT '入口重量',
  `id` varchar(200) NOT NULL COMMENT '交易流水号',
  `vlp` varchar(200) DEFAULT NULL COMMENT '车牌号',
  `station_receive_time` varchar(200) DEFAULT NULL COMMENT '站级接收时间',
  `trans_type` varchar(200) DEFAULT NULL COMMENT '交易类型',
  `over_weight_rate` int DEFAULT NULL COMMENT '超限率',
  `trans_code` varchar(200) DEFAULT NULL COMMENT '交易编码',
  `trans_fee` int DEFAULT NULL COMMENT '卡面扣费金额',
  `sp_info` varchar(200) DEFAULT NULL COMMENT '业务分析特情状态',
  `identify_vlp` varchar(200) DEFAULT NULL COMMENT '识别车牌号',
  `direction` int DEFAULT NULL COMMENT '行驶方向',
  `balance_before` varchar(200) DEFAULT NULL COMMENT '交易前余额（分）',
  `identify_vlpc` int DEFAULT NULL COMMENT '识别车牌颜色',
  `special_type` varchar(200) DEFAULT NULL COMMENT '部特情类型',
  `l_date` varchar(200) DEFAULT NULL COMMENT '逻辑日期',
  `lane_sp_info` varchar(300) DEFAULT NULL COMMENT '车道特情状态',
  `oper_id` varchar(200) DEFAULT NULL COMMENT '操作员工号',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='入口车道流水同步表';


-- gsdb310.exittransaction definition

CREATE TABLE `exittransaction` (
  `modify_flag` int DEFAULT NULL COMMENT '修改标志',
  `ticket_fee` bigint DEFAULT NULL COMMENT '次票代收',
  `unpay_flag` text COMMENT '欠通行费标志',
  `return_money_sn` text COMMENT '补费记录号',
  `collect_fee` bigint DEFAULT NULL COMMENT '代收外省金额',
  `oper_name` text COMMENT '操作员姓名',
  `free_mode` int DEFAULT NULL COMMENT '免费方式',
  `receive_time` datetime DEFAULT NULL COMMENT '接收时间',
  `unpay_card_cost` bigint DEFAULT NULL COMMENT '欠卡成本金额(分）',
  `ex_toll_station_name` text COMMENT '出口收费站名称',
  `id` varchar(255) NOT NULL COMMENT '交易流水号',
  `pay_card_id` text COMMENT '支付卡卡号',
  `unpay_fee` bigint DEFAULT NULL COMMENT '欠通行费金额(分）',
  `station_receive_time` datetime DEFAULT NULL COMMENT '站级接收时间',
  `trans_type` text COMMENT '交易类型',
  `over_weight_rate` int DEFAULT NULL COMMENT '超限率',
  `obu_pay_fee` bigint DEFAULT NULL COMMENT 'OBU应收金额',
  `pay_fee` bigint DEFAULT NULL COMMENT '应收金额',
  `trans_code` text COMMENT '交易编码',
  `sp_info` text COMMENT '业务分析特情状态',
  `trans_fee` bigint DEFAULT NULL COMMENT '卡面扣费金额',
  `en_last_money` bigint DEFAULT NULL COMMENT '本次最终支付通行费金额',
  `en_free_money` bigint DEFAULT NULL COMMENT '通行费免收金额（分）',
  `free_type` int DEFAULT NULL COMMENT '免费区间类型',
  `identify_vlp` text COMMENT '识别车牌号',
  `ex_toll_lane_id` text COMMENT '出口车道号(国标)',
  `pay_type` int DEFAULT NULL COMMENT '支付类型',
  `identify_vlpc` int DEFAULT NULL COMMENT '识别车牌颜色',
  `special_type` text COMMENT '部特情类型',
  `ex_vlp` text COMMENT '出口实际车牌号',
  `l_date` datetime DEFAULT NULL COMMENT '逻辑日期',
  `ex_time` datetime DEFAULT NULL COMMENT '出口时间',
  `oper_id` text COMMENT '操作员工号',
  `toll_province_id` text COMMENT '出口省中心 Id',
  `limit_weight` int DEFAULT NULL COMMENT '限载总重(kg)',
  `media_type` int DEFAULT NULL COMMENT '通行介质类型',
  `source_id` text COMMENT '原始流水号',
  `real_distance` int DEFAULT NULL COMMENT '实际里程(米)',
  `axle_count` int DEFAULT NULL COMMENT '轴数',
  `trans_pay_type` int DEFAULT NULL COMMENT '交易支付方式',
  `pass_id` text COMMENT '通行标识ID',
  `ex_weight` int DEFAULT NULL COMMENT '出口重量',
  `rebate_money` bigint DEFAULT NULL COMMENT '折扣优惠金额(分)',
  `description` text COMMENT '交易描述',
  `axis_info` text COMMENT '轴组信息',
  `media_no` text COMMENT '通行介质编码',
  `balance_after` bigint DEFAULT NULL COMMENT '交易后余额（分）',
  `fee_mileage` bigint DEFAULT NULL COMMENT '计费总里程数',
  `en_toll_money` bigint DEFAULT NULL COMMENT '应收通行费金额(分)',
  `discount_fee` bigint DEFAULT NULL COMMENT '优惠金额',
  `ex_vlpc` int DEFAULT NULL COMMENT '出口实际车牌颜色',
  `toll_distance` int DEFAULT NULL COMMENT '计费里程（米）',
  `free_info` text COMMENT '免费区域信息',
  `v_speed` int DEFAULT NULL COMMENT '特情处理类型',
  `fee` bigint DEFAULT NULL COMMENT '总交易金额',
  `province_group` text COMMENT '省中心编号组合',
  `balance_before` bigint DEFAULT NULL COMMENT '交易前余额（分）',
  `card_cost_fee` bigint DEFAULT NULL COMMENT '卡成本金额(分)',
  `ex_toll_station_id` text COMMENT '出口站号(国标)',
  `obu_discount_fee` bigint DEFAULT NULL COMMENT 'OBU优惠金额',
  `lane_sp_info` text COMMENT '车道特情状态',
  `multi_province` int DEFAULT NULL COMMENT '是否多省交易',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='出口车道流水同步表';


-- gsdb310.gantrytransaction definition

CREATE TABLE `gantrytransaction` (
  `id` varchar(255) NOT NULL,
  `toll_interval_id` varchar(200) DEFAULT NULL COMMENT '收费单元编号组合',
  `charges_special_type` varchar(200) DEFAULT NULL COMMENT '收费特情类型',
  `gantry_type` varchar(200) DEFAULT NULL COMMENT '门架类型',
  `vlpc` int DEFAULT NULL COMMENT '计费车牌颜色',
  `media_type` int DEFAULT NULL COMMENT '通行介质类型',
  `trans_time` datetime DEFAULT NULL COMMENT '计费交易时间',
  `gantry_id` varchar(200) DEFAULT NULL COMMENT '门架编号',
  `axle_count` int DEFAULT NULL COMMENT '车轴数',
  `last_gantry_hex` varchar(200) DEFAULT NULL COMMENT '上个门架hex编码',
  `total_weight` int DEFAULT NULL COMMENT '车货总重',
  `pass_id` varchar(200) DEFAULT NULL COMMENT '通行标识 ID',
  `receive_time` datetime DEFAULT NULL COMMENT '接收时间',
  `fee_calc_special` int DEFAULT NULL COMMENT '计费接口特情值',
  `pay_fee_group` varchar(200) DEFAULT NULL COMMENT '应收金额组合',
  `fee_group` varchar(200) DEFAULT NULL COMMENT '交易金额组合',
  `description` varchar(200) DEFAULT NULL COMMENT '对交易的文字解释',
  `toll_interval_sign` varchar(200) DEFAULT NULL COMMENT '收费单元处理标识',
  `vlp` varchar(200) DEFAULT NULL COMMENT '计费车牌号',
  `fee_mileage` int DEFAULT NULL COMMENT '计费里程数',
  `balance_after` bigint DEFAULT NULL COMMENT '交易后余额（分）',
  `pay_fee` bigint DEFAULT NULL COMMENT '应收金额',
  `discount_fee` bigint DEFAULT NULL COMMENT '优惠金额',
  `trans_fee` bigint DEFAULT NULL COMMENT '卡面扣费金额',
  `identify_vehicle_type` int DEFAULT NULL COMMENT '识别的车型',
  `gantry_hex` varchar(200) DEFAULT NULL COMMENT '门架HEX值',
  `fee` bigint DEFAULT NULL COMMENT '交易金额',
  `vehicle_length` int DEFAULT NULL COMMENT '车辆长',
  `record_gen_time` datetime DEFAULT NULL COMMENT '记录生成时间',
  `last_gantry_time` datetime DEFAULT NULL COMMENT '通过上个门架的时间',
  `vehicle_width` int DEFAULT NULL COMMENT '车辆宽',
  `balance_before` bigint DEFAULT NULL COMMENT '交易前余额（分）',
  `original_flag` int DEFAULT NULL COMMENT '数据来源',
  `trade_id` varchar(200) NOT NULL COMMENT '计费交易编号',
  `cpu_card_id` varchar(200) DEFAULT NULL COMMENT 'CPU卡编号',
  `is_fix_data` int DEFAULT NULL COMMENT '是否修正过',
  `trade_type` int DEFAULT NULL COMMENT '交易类型',
  `vehicle_hight` int DEFAULT NULL COMMENT '车辆高',
  `vehicle_type` int DEFAULT NULL COMMENT '计费车型',
  `discount_fee_group` varchar(200) DEFAULT NULL COMMENT '优惠金额组合',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='ETC门架计费流水同步表';


-- gsdb310.`path` definition

CREATE TABLE `path` (
  `id` varchar(255) NOT NULL,
  `plate_color` int DEFAULT NULL COMMENT '车牌颜色',
  `en_time` varchar(200) DEFAULT NULL COMMENT '入口时间',
  `ex_toll_lane_id` varchar(200) DEFAULT NULL COMMENT '出口车道编号',
  `en_toll_lane_id` varchar(200) DEFAULT NULL COMMENT '入口车道编号',
  `ex_vehicle_type` int DEFAULT NULL COMMENT '出口车辆类型',
  `en_toll_station_id` varchar(200) DEFAULT NULL COMMENT '入口收费站编号',
  `pay_type` int DEFAULT NULL COMMENT '支付类型',
  `ex_toll_station_id` varchar(200) DEFAULT NULL COMMENT '出口收费站编号',
  `pay_card_type` int DEFAULT NULL COMMENT '支付卡类型',
  `pass_id` varchar(200) DEFAULT NULL COMMENT '通行标识',
  `plate_num` varchar(200) DEFAULT NULL COMMENT '车牌号码',
  `l_date` varchar(100) DEFAULT NULL COMMENT '逻辑日期',
  `ex_time` varchar(200) DEFAULT NULL COMMENT '出口时间',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='车辆通行路径同步表';


-- gsdb310.pathdetail definition

CREATE TABLE `pathdetail` (
  `pass_id` varchar(200) DEFAULT NULL COMMENT '通行标识',
  `plate_num` varchar(200) DEFAULT NULL COMMENT '车牌号码',
  `plate_color` int DEFAULT NULL COMMENT '车牌颜色',
  `identify_point_hex` varchar(200) DEFAULT NULL COMMENT '标识点Hex码',
  `fee` varchar(200) DEFAULT NULL COMMENT '收费单元费用，多个费用使用"|"隔开',
  `trans_time` varchar(200) DEFAULT NULL COMMENT '交易时间',
  `intervals` varchar(200) DEFAULT NULL COMMENT '收费单元编号，多个编号使用"|"隔开',
  `id` varchar(200) NOT NULL COMMENT '交易标识',
  `identify_point_id` varchar(200) DEFAULT NULL COMMENT '标识点标识',
  `pay_fee` varchar(200) DEFAULT NULL COMMENT '收费单元支付费用，多个费用使用"|"隔开',
  `discount_fee` varchar(200) DEFAULT NULL COMMENT '收费单元优惠费用，多个费用使用"|"隔开',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='车辆通行路径明细同步表';


-- gsdb310.splitdetail definition

CREATE TABLE `splitdetail` (
  `id` varchar(255) NOT NULL,
  `toll_interval_pay_fee` varchar(200) DEFAULT NULL COMMENT '收费单元支付费用',
  `toll_interval_fee` varchar(200) DEFAULT NULL COMMENT '收费单元费用',
  `pass_id` varchar(200) NOT NULL COMMENT '通行标识',
  `interval_id` varchar(200) NOT NULL COMMENT '收费单元编号',
  `split_remark` varchar(200) DEFAULT NULL COMMENT '拆分备注',
  `pro_split_time` varchar(200) DEFAULT NULL COMMENT '拆分时间',
  `pro_split_type` int DEFAULT NULL COMMENT '拆分原则',
  `transaction_id` varchar(200) NOT NULL COMMENT '交易编号',
  `split_flag` int DEFAULT NULL COMMENT '拆分标志',
  `toll_interval_discount_fee` varchar(200) DEFAULT NULL COMMENT '收费单元优惠费用',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='拆分明细同步表';


-- gsdb310.tollinterval definition

CREATE TABLE `tollinterval` (
  `response_code` bigint NOT NULL COMMENT '系统响应代码',
  `section_id` varchar(16) DEFAULT NULL COMMENT 'id截取前11位为路段ID',
  `end_lng` varchar(20) DEFAULT NULL COMMENT '终点经度',
  `start_stake_num` varchar(20) NOT NULL COMMENT '起点桩号',
  `end_time` datetime NOT NULL COMMENT '收费单元结束时间',
  `length` bigint NOT NULL COMMENT '收费单元长度',
  `end_lat` varchar(20) DEFAULT NULL COMMENT '终点纬度',
  `vertical_section_type` bigint DEFAULT NULL COMMENT '垂直断面类型',
  `receive_time` datetime DEFAULT NULL COMMENT '数据接收时间',
  `status` bigint DEFAULT NULL COMMENT '收费单元状态',
  `id` varchar(16) NOT NULL COMMENT '主键ID',
  `type` bigint NOT NULL COMMENT '收费单元类型',
  `response_info` varchar(1024) DEFAULT NULL COMMENT '系统响应信息',
  `batch_file_name` varchar(128) DEFAULT NULL COMMENT '批次处理文件名',
  `start_lat` varchar(20) DEFAULT NULL COMMENT '起点纬度',
  `start_lng` varchar(20) DEFAULT NULL COMMENT '起点经度',
  `begin_time` datetime NOT NULL COMMENT '收费单元开始时间',
  `direction` bigint DEFAULT NULL COMMENT '通行方向',
  `record_gen_time` datetime NOT NULL COMMENT '记录生成时间',
  `end_stake_num` varchar(20) NOT NULL COMMENT '终点桩号',
  `name` varchar(150) NOT NULL COMMENT '收费单元名称',
  `operation` bigint NOT NULL COMMENT '操作类型',
  `province_type` bigint NOT NULL COMMENT '省份类型',
  `pro_time` datetime DEFAULT NULL COMMENT '系统处理时间',
  `toll_roads` varchar(150) NOT NULL COMMENT '收费道路信息',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='收费单元同步表';


-- gsdb310.tollsection definition

CREATE TABLE `tollsection` (
  `start_lng` varchar(20) NOT NULL COMMENT '起点经度',
  `end_lng` varchar(20) NOT NULL COMMENT '终点经度',
  `start_stake_num` varchar(20) NOT NULL COMMENT '起点桩号',
  `end_time` datetime NOT NULL COMMENT '结束时间',
  `length` bigint NOT NULL COMMENT '长度',
  `record_gen_time` datetime DEFAULT NULL COMMENT '记录生成时间',
  `tax` bigint NOT NULL COMMENT '税费',
  `end_stake_num` varchar(20) NOT NULL COMMENT '终点桩号',
  `end_lat` varchar(20) NOT NULL COMMENT '终点纬度',
  `name` varchar(150) NOT NULL COMMENT '名称',
  `charge_type` bigint NOT NULL COMMENT '收费类型',
  `status` varchar(1) DEFAULT NULL COMMENT '状态',
  `section_owner_id` varchar(7) NOT NULL COMMENT '路段所有者ID',
  `start_time` datetime NOT NULL COMMENT '开始时间',
  `operation` bigint NOT NULL COMMENT '操作',
  `id` varchar(11) NOT NULL COMMENT '路段ID（主键）',
  `toll_roads` varchar(150) NOT NULL COMMENT '收费路段',
  `type` bigint NOT NULL COMMENT '类型',
  `road_id` varchar(12) NOT NULL COMMENT '道路ID',
  `start_lat` varchar(20) NOT NULL COMMENT '起点纬度',
  `tax_rate` varchar(16) NOT NULL COMMENT '税率',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='收费路段同步表';