-- gs0115.clearreport definition

CREATE TABLE `clearreport` (
  `crop_id` int DEFAULT NULL COMMENT '收费路段业主',
  `road_id` varchar(255) DEFAULT NULL COMMENT '收费公路',
  `split_org` varchar(255) DEFAULT NULL COMMENT '拆分机构',
  `org_type` int DEFAULT NULL COMMENT '机构类型',
  `pay_card_type` int DEFAULT NULL COMMENT '支付卡类型',
  `money_flag` int DEFAULT NULL COMMENT '金额标志',
  `clear_date` date DEFAULT NULL COMMENT '清分日期',
  `l_date` date DEFAULT NULL COMMENT '逻辑日期',
  `gen_time` date DEFAULT NULL COMMENT '生成时间',
  `cash_split_money` decimal(18,2) DEFAULT NULL COMMENT '现金拆分金额',
  `cash_op_split_money` decimal(18,2) DEFAULT NULL COMMENT '现金操作拆分金额',
  `cash_toll_money` decimal(18,2) DEFAULT NULL COMMENT '现金合计金额',
  `cash_op_toll_money` decimal(18,2) DEFAULT NULL COMMENT '现金操作合计金额',
  `other_split_money` decimal(18,2) DEFAULT NULL COMMENT '其他拆分金额',
  `other_op_split_money` decimal(18,2) DEFAULT NULL COMMENT '其他操作拆分金额',
  `other_toll_money` decimal(18,2) DEFAULT NULL COMMENT '其他合计金额',
  `other_op_toll_money` decimal(18,2) DEFAULT NULL COMMENT '其他操作合计金额',
  `union_split_money` decimal(18,2) DEFAULT NULL COMMENT '联合拆分金额',
  `union_op_split_money` decimal(18,2) DEFAULT NULL COMMENT '联合操作拆分金额',
  `union_toll_money` decimal(18,2) DEFAULT NULL COMMENT '联合合计金额',
  `union_op_toll_money` decimal(18,2) DEFAULT NULL COMMENT '联合操作合计金额',
  `etc_split_money` decimal(18,2) DEFAULT NULL COMMENT 'ETC拆分金额',
  `etc_op_split_money` decimal(18,2) DEFAULT NULL COMMENT 'ETC操作拆分金额',
  `etc_toll_money` decimal(18,2) DEFAULT NULL COMMENT 'ETC合计金额',
  `etc_op_toll_money` decimal(18,2) DEFAULT NULL COMMENT 'ETC操作合计金额',
  `alipay_split_money` decimal(18,2) DEFAULT NULL COMMENT '支付宝拆分金额',
  `alipay_op_split_money` decimal(18,2) DEFAULT NULL COMMENT '支付宝操作拆分金额',
  `alipay_toll_money` decimal(18,2) DEFAULT NULL COMMENT '支付宝合计金额',
  `alipay_op_toll_money` decimal(18,2) DEFAULT NULL COMMENT '支付宝操作合计金额',
  `wepay_split_money` decimal(18,2) DEFAULT NULL COMMENT '微信拆分金额',
  `wepay_op_split_money` decimal(18,2) DEFAULT NULL COMMENT '微信操作拆分金额',
  `wepay_toll_money` decimal(18,2) DEFAULT NULL COMMENT '微信合计金额',
  `wepay_op_toll_money` decimal(18,2) DEFAULT NULL COMMENT '微信操作合计金额',
  `cash_return_money` decimal(18,2) DEFAULT NULL COMMENT '现金退费金额',
  `other_return_money` decimal(18,2) DEFAULT NULL COMMENT '其他退费金额',
  `union_return_money` decimal(18,2) DEFAULT NULL COMMENT '联合退费金额',
  `etc_return_money` decimal(18,2) DEFAULT NULL COMMENT 'ETC退费金额',
  `alipay_return_money` decimal(18,2) DEFAULT NULL COMMENT '支付宝退费金额',
  `wepay_return_money` decimal(18,2) DEFAULT NULL COMMENT '微信退费金额'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='清分报表';


-- gs0115.clearresult definition

CREATE TABLE `clearresult` (
  `pass_id` varchar(255) DEFAULT NULL COMMENT '通行标识',
  `transaction_id` varchar(255) DEFAULT NULL COMMENT '交易编号',
  `interval_id` varchar(255) DEFAULT NULL COMMENT '收费单元编号',
  `crop_id` int DEFAULT NULL COMMENT '收费路段业主',
  `road_id` varchar(255) DEFAULT NULL COMMENT '收费公路',
  `pay_type` int DEFAULT NULL COMMENT '支付方式',
  `pay_card_type` int DEFAULT NULL COMMENT '支付卡类型',
  `amount` decimal(18,2) DEFAULT NULL COMMENT '实收清分金额',
  `discount_amount` decimal(18,2) DEFAULT NULL COMMENT '优惠清分金额',
  `charge_amount` decimal(18,2) DEFAULT NULL COMMENT '应收清分金额',
  `clear_date` date DEFAULT NULL COMMENT '清分日期',
  `l_date` date DEFAULT NULL COMMENT '逻辑日'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='清分结果';


-- gs0115.entrytransaction definition

CREATE TABLE `entrytransaction` (
  `ID` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `PASSID` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LDATE` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENTIME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `STATIONRECEIVETIME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RECEIVETIME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `OPERID` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `OPERNAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENTOLLLANEID` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `MEDIATYPE` int DEFAULT NULL,
  `OBUID` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `VLP` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `VLPC` int DEFAULT NULL,
  `IDENTIFYVLP` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `IDENTIFYVLPC` int DEFAULT NULL,
  `TRANSCODE` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TRANSTYPE` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `BALANCEBEFORE` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TRANSFEE` int DEFAULT NULL,
  `DIRECTION` int DEFAULT NULL,
  `ENAXLECOUNT` int DEFAULT NULL,
  `AXISINFO` int DEFAULT NULL,
  `ENWEIGHT` int DEFAULT NULL,
  `LIMITWEIGHT` int DEFAULT NULL,
  `OVERWEIGHTRATE` int DEFAULT NULL,
  `DESCRIPTION` int DEFAULT NULL,
  `SPECIALTYPE` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LANESPINFO` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SPINFO` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- gs0115.exittransaction definition

CREATE TABLE `exittransaction` (
  `ID` longtext COLLATE utf8mb4_unicode_ci,
  `PASSID` longtext COLLATE utf8mb4_unicode_ci,
  `SOURCEID` longtext COLLATE utf8mb4_unicode_ci,
  `RETURNMONEYSN` longtext COLLATE utf8mb4_unicode_ci,
  `LDATE` datetime DEFAULT NULL,
  `EXTIME` datetime DEFAULT NULL,
  `STATIONRECEIVETIME` datetime DEFAULT NULL,
  `RECEIVETIME` datetime DEFAULT NULL,
  `OPERID` longtext COLLATE utf8mb4_unicode_ci,
  `OPERNAME` longtext COLLATE utf8mb4_unicode_ci,
  `EXTOLLLANEID` longtext COLLATE utf8mb4_unicode_ci,
  `EXTOLLSTATIONID` longtext COLLATE utf8mb4_unicode_ci,
  `EXTOLLSTATIONNAME` longtext COLLATE utf8mb4_unicode_ci,
  `MEDIATYPE` int DEFAULT NULL,
  `MEDIANO` longtext COLLATE utf8mb4_unicode_ci,
  `EXVLP` longtext COLLATE utf8mb4_unicode_ci,
  `EXVLPC` int DEFAULT NULL,
  `IDENTIFYVLP` longtext COLLATE utf8mb4_unicode_ci,
  `IDENTIFYVLPC` int DEFAULT NULL,
  `TRANSCODE` longtext COLLATE utf8mb4_unicode_ci,
  `TRANSTYPE` longtext COLLATE utf8mb4_unicode_ci,
  `MULTIPROVINCE` int DEFAULT NULL,
  `PROVINCEGROUP` longtext COLLATE utf8mb4_unicode_ci,
  `TOLLPROVINCEID` longtext COLLATE utf8mb4_unicode_ci,
  `TRANSPAYTYPE` int DEFAULT NULL,
  `PAYTYPE` int DEFAULT NULL,
  `PAYCARDID` longtext COLLATE utf8mb4_unicode_ci,
  `AXLECOUNT` int DEFAULT NULL,
  `AXISINFO` longtext COLLATE utf8mb4_unicode_ci,
  `EXWEIGHT` int DEFAULT NULL,
  `LIMITWEIGHT` int DEFAULT NULL,
  `OVERWEIGHTRATE` int DEFAULT NULL,
  `DESCRIPTION` longtext COLLATE utf8mb4_unicode_ci,
  `VSPEED` int DEFAULT NULL,
  `SPECIALTYPE` longtext COLLATE utf8mb4_unicode_ci,
  `LANESPINFO` longtext COLLATE utf8mb4_unicode_ci,
  `SPINFO` longtext COLLATE utf8mb4_unicode_ci,
  `MODIFYFLAG` int DEFAULT NULL,
  `TOLLDISTANCE` int DEFAULT NULL,
  `REALDISTANCE` int DEFAULT NULL,
  `FREETYPE` int DEFAULT NULL,
  `FREEMODE` int DEFAULT NULL,
  `FREEINFO` longtext COLLATE utf8mb4_unicode_ci,
  `TRANSFEE` bigint DEFAULT NULL,
  `BALANCEBEFORE` bigint DEFAULT NULL,
  `BALANCEAFTER` bigint DEFAULT NULL,
  `FEE` bigint DEFAULT NULL,
  `DISCOUNTFEE` bigint DEFAULT NULL,
  `PAYFEE` bigint DEFAULT NULL,
  `OBUPAYFEE` bigint DEFAULT NULL,
  `OBUDISCOUNTFEE` bigint DEFAULT NULL,
  `FEEMILEAGE` bigint DEFAULT NULL,
  `COLLECTFEE` bigint DEFAULT NULL,
  `REBATEMONEY` bigint DEFAULT NULL,
  `CARDCOSTFEE` bigint DEFAULT NULL,
  `UNPAYFEE` bigint DEFAULT NULL,
  `UNPAYFLAG` longtext COLLATE utf8mb4_unicode_ci,
  `UNPAYCARDCOST` bigint DEFAULT NULL,
  `TICKETFEE` bigint DEFAULT NULL,
  `ENTOLLMONEY` bigint DEFAULT NULL,
  `ENFREEMONEY` bigint DEFAULT NULL,
  `ENLASTMONEY` bigint DEFAULT NULL,
  `EXITEXTLIST` longtext COLLATE utf8mb4_unicode_ci
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- gs0115.gantrytransaction definition

CREATE TABLE `gantrytransaction` (
  `TRADEID` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `PASSID` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TRANSTIME` datetime DEFAULT NULL,
  `RECORDGENTIME` datetime DEFAULT CURRENT_TIMESTAMP,
  `RECEIVETIME` datetime DEFAULT CURRENT_TIMESTAMP,
  `GANTRYID` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `GANTRYTYPE` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ORIGINALFLAG` int DEFAULT NULL,
  `GANTRYHEX` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LASTGANTRYHEX` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LASTGANTRYTIME` datetime DEFAULT NULL,
  `MEDIATYPE` int DEFAULT NULL,
  `CPUCARDID` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `VLP` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `VLPC` int DEFAULT NULL,
  `VEHICLETYPE` int DEFAULT NULL,
  `IDENTIFYVEHICLETYPE` int DEFAULT NULL,
  `TRADETYPE` int DEFAULT '-1',
  `AXLECOUNT` int DEFAULT NULL,
  `TOTALWEIGHT` int DEFAULT NULL,
  `VEHICLELENGTH` int DEFAULT NULL,
  `VEHICLEWIDTH` int DEFAULT NULL,
  `VEHICLEHIGHT` int DEFAULT NULL,
  `FEEMILEAGE` int DEFAULT NULL,
  `TRANSFEE` bigint DEFAULT NULL,
  `BALANCEBEFORE` bigint DEFAULT NULL,
  `BALANCEAFTER` bigint DEFAULT NULL,
  `PAYFEE` bigint DEFAULT NULL,
  `FEE` bigint DEFAULT NULL,
  `DISCOUNTFEE` bigint DEFAULT NULL,
  `TOLLINTERVALID` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TOLLINTERVALSIGN` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PAYFEEGROUP` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FEEGROUP` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `DISCOUNTFEEGROUP` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `DESCRIPTION` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FEECALCSPECIAL` int DEFAULT '-1',
  `CHARGESSPECIALTYPE` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ISFIXDATA` int DEFAULT '0',
  PRIMARY KEY (`TRADEID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- gs0115.`path` definition

CREATE TABLE `path` (
  `ID` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `PASSID` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PLATENUM` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PLATECOLOR` int DEFAULT NULL,
  `ENTIME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `EXTIME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENTOLLLANEID` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `EXTOLLLANEID` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENTOLLSTATIONID` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `EXTOLLSTATIONID` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `EXVEHICLETYPE` int DEFAULT NULL,
  `PAYTYPE` int DEFAULT NULL,
  `PAYCARDTYPE` int DEFAULT NULL,
  `LDATE` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- gs0115.pathdetail definition

CREATE TABLE `pathdetail` (
  `ID` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `PASSID` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PLATENUM` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PLATECOLOR` int DEFAULT NULL,
  `IDENTIFYPOINTID` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `IDENTIFYPOINTHEX` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `INTERVALS` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FEE` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PAYFEE` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `DISCOUNTFEE` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TRANSTIME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- gs0115.sectionowner definition

CREATE TABLE `sectionowner` (
  `ID` char(7) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `OWNERID` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `NAME` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `CONTACT` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `TEL` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `ADDRESS` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `BANK` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `BANKADDR` varchar(300) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `BANKACCOUNT` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TAXPAYERCODE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CREDITCODE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `OPERATION` bigint NOT NULL,
  `RECORDGENTIME` datetime DEFAULT NULL,
  `STATUS` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '0',
  `BATCHFILENAME` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RESPONSECODE` bigint DEFAULT '0',
  `RESPONSEINFO` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RECEIVETIME` datetime DEFAULT NULL,
  `PROTIME` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- gs0115.splitdetail definition

CREATE TABLE `splitdetail` (
  `PASSID` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `TRANSACTIONID` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `INTERVALID` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TOLLINTERVALFEE` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TOLLINTERVALPAYFEE` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TOLLINTERVALDISCOUNTFEE` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SPLITFLAG` int DEFAULT NULL,
  `PROSPLITTIME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PROSPLITTYPE` int DEFAULT NULL,
  `SPLITREMARK` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- gs0115.tollgantry definition

CREATE TABLE `tollgantry` (
  `ID` char(19) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `NAME` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TYPE` bigint NOT NULL,
  `TOLLINTERVALS` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `LAT` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `LNG` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `PILENUMBER` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `STATUS` bigint NOT NULL DEFAULT '0',
  `STARTTIME` datetime NOT NULL,
  `ENDTIME` datetime NOT NULL DEFAULT '2999-12-31 00:00:00',
  `ETCGANTRYHEX` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `RSUMANUID` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `RSUMODEL` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `RSUID` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `VPLRUID` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `VPLRMODEL` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `VPLRID` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `HDVUID` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `HDVMODEL` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `HDVID` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `OPERATION` bigint NOT NULL,
  `RECORDGENTIME` datetime NOT NULL,
  `RESPONSECODE` bigint NOT NULL DEFAULT '0',
  `RESPONSEINFO` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RECEIVETIME` datetime DEFAULT NULL,
  `PROTIME` datetime DEFAULT NULL,
  `BATCHFILENAME` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `BOUNDARYTYPE` bigint DEFAULT NULL,
  `CONTROLLERUID` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `CONTROLLERMODEL` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `CONTROLLERID` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `CONTROLLERSYSVER` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `SERVERUID` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `SERVERMODEL` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `SERVERID` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `SERVERSYSVER` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `SERVERDBVER` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `VEHDETECTORUID` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `VEHDETECTORMODEL` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `VEHDETECTORID` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `WEATHERDETECTORUID` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `WEATHERDETECTORMODEL` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `WEATHERDETECTORID` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CLASSDETECTORUID` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CLASSDETECTORMODEL` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CLASSDETECTORID` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LOADDETECTIONUID` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LOADDETECTIONMODEL` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LOADDETECTIONID` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TEMPCONTROLLERUID` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TEMPCONTROLLERMODEL` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TEMPCONTROLLERID` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `POWERCONTROLLERUID` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `POWERCONTROLLERMODEL` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `POWERCONTROLLERID` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SAFEEQUIPUID` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SAFEEQUIPMODEL` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SAFEEQUIPID` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LINETYPE` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `OPERATORS` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `DATAMERGEPOINT` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `IMEI` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `EQUIPMENTIP` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SNMPVERSION` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SNMPPORT` bigint DEFAULT '161',
  `COMMUNITY` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SECURITYNAME` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SECURITYLEVEL` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `AUTHENTICATION` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `AUTHKEY` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENCRYPTION` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SECRETKEY` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `USESTATUS` bigint NOT NULL,
  `GANTARYTYPE` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LANECOUNT` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REETCGANTRYHEX` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `AGENCYGANTRYIDS` varchar(19) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `GANTRYSIGN` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- gs0115.tollinterval definition

CREATE TABLE `tollinterval` (
  `ID` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `SECTIONID` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAME` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `TYPE` bigint NOT NULL,
  `LENGTH` bigint NOT NULL,
  `STARTLAT` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `STARTLNG` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `STARTSTAKENUM` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `ENDSTAKENUM` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `ENDLAT` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ENDLNG` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TOLLROADS` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `PROVINCETYPE` bigint NOT NULL,
  `ENDTIME` datetime NOT NULL,
  `OPERATION` bigint NOT NULL,
  `RECORDGENTIME` datetime NOT NULL,
  `RESPONSECODE` bigint NOT NULL,
  `RESPONSEINFO` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RECEIVETIME` datetime DEFAULT NULL,
  `PROTIME` datetime DEFAULT NULL,
  `BATCHFILENAME` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `STATUS` bigint DEFAULT '0',
  `DIRECTION` bigint DEFAULT NULL,
  `BEGINTIME` datetime NOT NULL DEFAULT '2999-12-31 00:00:00',
  `VERTICALSECTIONTYPE` bigint DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- gs0115.tollsection definition

CREATE TABLE `tollsection` (
  `ID` char(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `ROADID` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `NAME` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `SECTIONOWNERID` char(7) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `TYPE` bigint NOT NULL,
  `LENGTH` bigint NOT NULL,
  `STARTSTAKENUM` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `STARTLAT` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `STARTLNG` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `ENDSTAKENUM` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `ENDLAT` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `ENDLNG` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `TAX` bigint NOT NULL,
  `TAXRATE` decimal(16,2) NOT NULL,
  `CHARGETYPE` bigint NOT NULL,
  `TOLLROADS` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `BUILTTIME` datetime NOT NULL,
  `STARTTIME` datetime NOT NULL,
  `ENDTIME` datetime NOT NULL,
  `OPERATION` bigint NOT NULL,
  `RECORDGENTIME` datetime DEFAULT NULL,
  `STATUS` char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '0',
  `BATCHFILENAME` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RESPONSECODE` bigint DEFAULT '0',
  `RESPONSEINFO` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RECEIVETIME` datetime DEFAULT NULL,
  `PROTIME` datetime DEFAULT NULL,
  `NEXTTAXRATE` decimal(16,2) DEFAULT NULL,
  `NEXTRATEDATE` datetime DEFAULT NULL,
  `SECTIONLEVEL` bigint DEFAULT NULL,
  `ONLINETYPE` bigint DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;