version: "1.0"
namespace: "com.tollcenter.ontology"

# 数据源连接配置（可选）
# 定义如何连接到外部数据库
# 如果 object_type 没有配置 data_source，则使用文件系统存储
data_sources:
  # H2 数据库示例（本地文件模式）
  - id: local_h2
    type: h2
    host: file  # file 表示文件模式，mem 表示内存模式，或指定 TCP 服务器地址
    port: 0  # 文件模式不需要端口
    database: mypalantir  # 数据库文件名（不含 .mv.db 后缀）
    username: sa
    password: ""  # H2 默认密码为空
    jdbc_url: jdbc:h2:file:./data/h2/mypalantir  # 文件将存储在 ./data/h2/mypalantir.mv.db
    properties:
      AUTO_SERVER: false  # 是否启用自动服务器模式
      DB_CLOSE_DELAY: -1  # 连接关闭后保持数据库打开的时间（-1 表示永久）

object_types:
  - name: 收费站
    description: "收费站对象"
    # 数据源映射配置：从 H2 数据库读取数据
    data_source:
      connection_id: local_h2
      table: toll_stations
      id_column: station_id
      field_mapping:
        名称: name
        省份: province
    properties:
      - name: 名称
        data_type: string
        required: true
        description: "收费站名称"
        constraints:
          min_length: 1
          max_length: 100
      
      - name: 省份
        data_type: string
        required: true
        description: "所属省份"
        constraints:
          min_length: 1
          max_length: 50

  - name: 收费记录
    description: "收费记录对象"
    # 数据源映射配置：从 H2 数据库读取数据
    data_source:
      connection_id: local_h2
      table: toll_records
      id_column: record_id
      field_mapping:
        收费站ID: station_id
        车辆ID: vehicle_id
        金额: amount
        收费时间: charge_time
    properties:
      - name: 收费站ID
        data_type: string
        required: true
        description: "收费站ID（外键）"
      
      - name: 车辆ID
        data_type: string
        required: true
        description: "车辆ID（外键）"
      
      - name: 金额
        data_type: float
        required: true
        description: "收费金额"
        constraints:
          min: 0
      
      - name: 收费时间
        data_type: datetime
        required: true
        description: "收费时间"

  - name: 车辆
    description: "车辆对象"
    # 数据源映射配置：从 H2 数据库读取数据
    data_source:
      connection_id: local_h2
      table: vehicles
      id_column: vehicle_id
      field_mapping:
        车牌号: plate_number
        车辆类型: vehicle_type
        车主姓名: owner_name
    properties:
      - name: 车牌号
        data_type: string
        required: true
        description: "车牌号"
        constraints:
          min_length: 1
          max_length: 20
      
      - name: 车辆类型
        data_type: string
        required: false
        description: "车辆类型"
      
      - name: 车主姓名
        data_type: string
        required: false
        description: "车主姓名"
        constraints:
          max_length: 100

  - name: 通行介质
    description: "通行介质对象（ETC卡、OBU等）"
    # 数据源映射配置：从 H2 数据库读取数据
    data_source:
      connection_id: local_h2
      table: media
      id_column: media_id
      field_mapping:
        介质编号: media_number
        介质类型: media_type
        发行日期: issue_date
    properties:
      - name: 介质编号
        data_type: string
        required: true
        description: "介质编号（唯一标识）"
        constraints:
          min_length: 1
          max_length: 50
      
      - name: 介质类型
        data_type: string
        required: true
        description: "介质类型（ETC卡、OBU等）"
        constraints:
          min_length: 1
          max_length: 50
      
      - name: 发行日期
        data_type: date
        required: false
        description: "发行日期"

link_types:
  - name: 拥有收费记录
    description: "收费站拥有收费记录"
    source_type: 收费站
    target_type: 收费记录
    cardinality: one-to-many
    direction: directed
    # 数据源映射配置：从 H2 数据库的中间表读取数据
    data_source:
      connection_id: local_h2
      table: toll_records
      id_column: record_id
      source_id_column: station_id  # 源对象（收费站）的ID列
      target_id_column: record_id   # 目标对象（收费记录）的ID列（自引用）

  - name: 拥有车辆记录
    description: "车辆拥有收费记录"
    source_type: 车辆
    target_type: 收费记录
    cardinality: one-to-many
    direction: directed
    # 数据源映射配置：从 H2 数据库的中间表读取数据
    data_source:
      connection_id: local_h2
      table: toll_records
      id_column: record_id
      source_id_column: vehicle_id  # 源对象（车辆）的ID列
      target_id_column: record_id   # 目标对象（收费记录）的ID列（自引用）

  - name: 持有
    description: "车辆持有通行介质（多对多关系，使用关系表模式）"
    source_type: 车辆
    target_type: 通行介质
    cardinality: many-to-many
    direction: undirected  # 无向关系，可以从任意方向查询
    # 数据源映射配置：使用独立的中间表存储关系（关系表模式）
    data_source:
      connection_id: local_h2
      table: vehicle_media  # 中间表，不同于车辆表和通行介质表
      id_column: link_id
      source_id_column: vehicle_id  # 源对象（车辆）的ID列
      target_id_column: media_id    # 目标对象（通行介质）的ID列
      link_mode: relation_table  # 显式指定为关系表模式
      field_mapping:
        绑定时间: bind_time
        绑定状态: bind_status
    properties:
      - name: 绑定时间
        data_type: datetime
        required: false
        description: "车辆与通行介质的绑定时间"
      
      - name: 绑定状态
        data_type: string
        required: false
        description: "绑定状态（已激活、已停用等）"
