version: "1.0"
namespace: "com.tollcenter.ontology"

object_types:
  - name: vehicle
    display_name: 车辆
    description: "车辆对象"
    properties:
      - name: plate_number
        display_name: 车牌号
        data_type: string
        required: true
        description: "车牌号码"
      
      - name: type
        display_name: 计费车型
        data_type: string
        required: false
        description: "不同计费车型享受不同的优惠政策"
      
      - name: vehicle_type
        display_name: 车辆类型
        data_type: string
        required: false
        description: "行驶证上登记的车辆类型"

  - name: medium
    display_name: 通行介质
    description: "通行介质（ETC卡、OBU等）"
    properties:
      - name: id
        display_name: 介质编号
        data_type: string
        required: true
        description: "介质唯一编号"
      
      - name: type
        display_name: 介质类型
        data_type: string
        required: true
        description: "介质类型（ETC卡、OBU等）"
      
      - name: issued_time
        display_name: 开卡时间
        data_type: date
        required: false
        description: "开卡时间"

link_types:
  - name: vehicle_has_medium
    display_name: 车辆持有通行介质
    description: "车辆持有通行介质"
    source_type: vehicle
    target_type: medium
    cardinality: one-to-many
    direction: directed
